### PR TITLE
Bucket::new() returns now a Result instead of Option

### LINKED ISSUE #29: `Bucket::new` should return a `Result`
`Bucket::new` may fail if the endpoint scheme is unsupported or if the url doesn't have a host.
This should return a `Result`, an `Option` doesn't reflect that something failed and can be silently ignored.

### PR DESCRIPTION
**Pull request by manuelpelloni**
Closes #29

### CODE REVIEW

File: src/bucket.rs [hunk 1]
```diff
@@ -41,12 +41,17 @@ use crate::Credentials;
...
 /// assert_eq!(bucket.object_url("duck.jpg").expect("url is valid").as_str(), "https://rusty-s3.s3-eu-west-1.amazonaws.com/duck.jpg");
 /// ```
-#[derive(Debug, Clone)]
+#[derive(Debug, Clone, PartialEq)]
 pub struct Bucket {
     base_url: Url,
     name: String,
     region: String,
 }
+#[derive(Debug, Copy, Clone, PartialEq)]
```
Comment (paolobarbolini) [inline src/bucket.rs:50]:
```suggestion
}

#[derive(Debug, Copy, Clone, PartialEq)]
```

**Review by paolobarbolini — APPROVED** [review]
